# Generated by Django 4.2 on 2023-05-15 15:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=35, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('name2', models.CharField(max_length=35, verbose_name='Отчетсво')),
                ('position', models.CharField(default='...', max_length=35, verbose_name='Должность')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=35, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=35, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('name2', models.CharField(max_length=35, verbose_name='Отчетсво')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=35)),
                ('orders_col', models.IntegerField(default=0)),
                ('last_order_date', models.DateField(default=datetime.date.today, verbose_name='Дата последнего заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Принят', 'Принят'), ('В работе', 'В работе'), ('Готов к выдаче', 'Готов к выдаче'), ('Выдан', 'Выдан'), ('Отменен', 'Отменен')], default='Принят', max_length=20, verbose_name='Статус заказа')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='Дата заказа')),
                ('comment', models.CharField(default='Пусто', max_length=200, verbose_name='Комментарий')),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name='Исполнитель')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users', verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orders')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.services')),
            ],
        ),
    ]
